services:
  - type: web
    name: flostfound-app
    env: python
    region: singapore
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT run:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: flostfound-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: flostfound-db
    databaseName: flostfound
    user: flostfound_user
    plan: free
